# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  yuido.oauth2.storage.jwt:
    class: AppBundle\JwtStorage
    arguments:
    - %private_key%
    - %public_key%

  yuido.oauth2.server:
    class: OAuth2\Server
    arguments:
     storage:
        - @oauth2.storage.client_credentials
        - @oauth2.storage.access_token
        - @oauth2.storage.authorization_code
        - @oauth2.storage.user_credentials
        - @oauth2.storage.refresh_token
        - @oauth2.storage.scope
        - @yuido.oauth2.storage.jwt

  yuido.oauth2.user_provider:
    class: AppBundle\User\OAuth2UserProvider
    arguments:
      - @doctrine.orm.entity_manager
      - @security.encoder_factory